---
config:
  flowchart:
    curve: linear
---
graph TD;
	__start__([<p>__start__</p>]):::first
	orchestrate(orchestrate)
	intent(intent)
	retrieve(retrieve)
	validate(validate)
	refine(refine)
	plan(plan)
	write(write)
	review(review)
	finalize(finalize)
	__end__([<p>__end__</p>]):::last
	__start__ --> intent;
	intent --> retrieve;
	orchestrate -.-> finalize;
	orchestrate -.-> plan;
	orchestrate -.-> refine;
	orchestrate -.-> write;
	plan --> write;
	refine --> retrieve;
	retrieve --> validate;
	review --> orchestrate;
	validate --> orchestrate;
	write --> review;
	finalize --> __end__;
	classDef default fill:#f2f0ff,line-height:1.2
	classDef first fill-opacity:0
	classDef last fill:#bfb6fc
